version: '3.3'
networks:
  chr-net:
    driver: bridge
    attachable: true
services:
  chr_db:
    container_name: chr_postgres
    image: postgres:13.0-alpine
    env_file:
      - ./backend/.envs/.env_db
    ports:
      - "5433:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data/
    networks:
      chr-net:
        aliases:
          - chr-database

  chr_backend:
    container_name: chr_backend
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.envs/.env_db
      - ./backend/.envs/.env_backend
    ports:
      - "8009:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - chr_db
    networks:
      chr-net:
        aliases:
          - chr-backend

volumes:
  pgdata:
